# Generated by Django 6.0.2 on 2026-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='finished_at',
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
